### ISSUE TITLE
Proper command management system

### ISSUE THREAD

**Issue by heftymouse** [EyeYouReadyForIt/EyeYouReadyForIt#21]
Currently we just have a switch statement that goes through all the slash commands that exist and then executes the right one. We also have to individually add every command to the registration method that we have. This should be made more dynamic, such that we can, for example, we can get all the classes that have a particular annotation/implement an interface, and then get its `ApplicationCommandRequest` and the method to handle that slash command from there

**Comment by heftymouse** [comment]
i made this sound way too complicated ugh

**Comment by heftymouse** [comment]
We aren't done yet:tm:

**Comment by BoogieMonster1O1** [comment]
yes

**Comment by BoogieMonster1O1** [comment]
we do reflections thing because yes

**Comment by BoogieMonster1O1** [comment]
Closed by #25
